### ISSUE TITLE
Server internal error using version 1.58 FMUSE

### ISSUE THREAD

**Issue by Shaw9682** [Unknown025/Flans-Mod-Plus#202] opened 2024-07-03 08:24 UTC
Hello!
I'm a 1.7.10 FMUSE server admin. My server upgraded FMUSE version from 1.56 to 1.58, which caused a problem that make players can not enter the server and feedback us with a internal server error. But the game still successly worked on singleplayer mode.

**Comment by Unknown025** [comment] 2024-07-03 09:11
That's curious, since I'm currently running v1.58 on my own server. Do you have a crash report or server/client log that might provide some details?

**Comment by Shaw9682** [comment] 2024-07-03 09:36
It's here.

**Comment by Shaw9682** [comment] 2024-07-03 09:45
I uploaded it, are you able to see it?

**Comment by Shaw9682** [comment] 2024-07-03 09:50
https://github.com/Shaw9682/Logs

(New to this website I don't know how to upload

**Comment by GoldSloth** [comment] 2024-07-03 12:10
Thanks for reporting this, looks like it's related to the recent change about food stats reflection @Unknown025.

**Comment by Shaw9682** [comment] 2024-07-03 13:00
No prob, will it be fixed soon?

**Comment by Unknown025** [comment] 2024-07-03 16:28
I'm not able to replicate this, do you have any mods installed that might change how hunger works?

**Comment by Shaw9682** [comment] 2024-07-03 16:32
No, there's only GVC and Custom NPC.

**Comment by Unknown025** [comment] 2024-07-03 16:56
Okay. I'm guessing you're using a Cauldron/Thermos derivative, does the issue occur if using a normal Forge server?

**Comment by Shaw9682** [comment] 2024-07-03 17:31
My server owner said the server is running on Uranium. We haven't tested it on Forge server because of plugin can't work on Forge server.our Uranium server which is based on mixture of mod and plugins(The community around my server is unwelcoming servers without plugins). And since my server are using our country's modder optimized platform. Uranium itself is based on consulting to Thermos, my server have to use this to get our plugin working on.

**Comment by Unknown025** [comment] 2024-07-03 17:49
Yup, that seems to be the issue, as they modify how how FoodStats are handled [here](https://github.com/UraniumMC/Uranium/blob/f73a12f22bda26b7db8bf2c80258c63767b272aa/patches/net/minecraft/entity/player/EntityPlayer.java.patch#L53). While I don't know exactly what @TheWillyJ was planning with his implementation, I'll rewrite it to not replace the original class.

**Comment by Shaw9682** [comment] 2024-07-03 18:00
Thanks, hoping it to be fixed soon.

**Comment by Unknown025** [comment] 2024-07-03 19:03
Fixed with the release of v1.59. Feel free to reopen if the issue is not solved.

**Closed as completed by Unknown025** 2024-07-03 19:03 UTC
Labels: bug
