### ISSUE TITLE
crash 1.56  Ultimate Stability Edition

### ISSUE THREAD

**Issue by Cronosus** [Unknown025/Flans-Mod-Plus#169] opened 2023-02-13 21:47 UTC
Hello
one of my players have random crash with this, can you help?

`Description: Unexpected error

java.lang.ClassCastException: com.flansmod.common.guns.EntityAAGun cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)`
	
packs:
Manus civil
Manus Dayz
minecraft smp parts
simple parts

**Comment by GoldSloth** [comment] 2023-02-13 22:58
Thanks for reporting, that's an interesting one - is this on a server, what other plugins/mods have you got running? Are you using any other mods to be spawn Flans vehicles, or does this occur when you right click to spawn an AA gun?

**Comment by Cronosus** [comment] 2023-02-14 17:05
it happens on server and in singleplayer too. this one i put here is from singleplayer log.
it happens when he placed some wehicles on ground. then he cant join/load anymore, until that vehicle is removed.
modpack is little big. ill ask him to try without other mods

ad. caused even without mods.
but were suspecting some incompatibility in civilian pack and aybe even dayz

**Comment by GoldSloth** [comment] 2023-02-14 17:59
I doubt this would be caused by a content pack issue, I would think it more likely that there was a conflict in some other mod he's using.

**Comment by Cronosus** [comment] 2023-02-14 18:27
> I doubt this would be caused by a content pack issue, I would think it more likely that there was a conflict in some other mod he's using.

nope, he tried using only flans mod + those content packs
from manus civil pack it looks like only police car wont crash it :D

**Comment by Cronosus** [comment] 2023-02-14 18:33
so he confirmed, except one, manus civil pack crash it, and all from dayz.. thats really weird

**Comment by GoldSloth** [comment] 2023-02-14 18:38
Could you send another crash report from one of these times, please? Unless they're all the same

**Comment by Cronosus** [comment] 2023-02-14 19:10
here some hserr (java)
[hs_err_pid6808.log](https://github.com/Unknown025/Flans-Mod-Plus/files/10735925/hs_err_pid6808.log)
and here log with new world and newly placed vehicle (crash right after)
[2023-02-14-7.log](https://github.com/Unknown025/Flans-Mod-Plus/files/10735948/2023-02-14-7.log)
here log from techniclauncher
[techniclauncher_2023-02-15.log](https://github.com/Unknown025/Flans-Mod-Plus/files/10735999/techniclauncher_2023-02-15.log)

for some reason theres no crash report, it simply just shut down

this is the old one
[2023-02-13-6.log](https://github.com/Unknown025/Flans-Mod-Plus/files/10735960/2023-02-13-6.log)

**Comment by GoldSloth** [comment] 2023-02-14 20:13
This hs_err is actually a different issue to the crash report attached, it's an error happening in native code (openGL) so it doesn't make a crash report. I'll look into both.

**Comment by GoldSloth** [comment] 2023-02-17 23:45
The second bug is a platofrm specific issue as I mentioned before, the issues is happenning inside an intel graphics driver (so they're probably using dedicated graphics). I can't offer much support on that I'm afraid - make sure he's using a dedicated GPU if he has one, it's quite common for people to forget to assign it. Otherwise, update graphics drivers, try messing around with video settings and potentially optifine settings too. Sorry I can't help much further.

I have seen other reports of the same bug with other versions of Flansmod, but I don't know what's causing it - other than it's Intel specific.

**Comment by Cronosus** [comment] 2023-02-17 23:51
looks like its by that integrated gpu. he had somehow older pc with intelgpu, but just today he get new pc with dedicated gpu, so hes fine now. :D
thanks anyway

**Comment by GoldSloth** [comment] 2023-02-18 08:02
Reopening since there was a second separate issue you posted here e.e

**Comment by GoldSloth** [comment] 2023-02-18 22:38
As for the initial issue, I've investigated further - and a packet is being received on the client for Minecraft to spawn a "normal" mob (like a zombie), but specifying it to be an AAGun, which isn't. I don't think the packet is coming from Flansmod, and I can't trace its origin any further. I'm pretty sure this is due to another mod, and I've seen similar other reports on the web too. Reopen if it still happens without any other mods.

**Closed as completed by GoldSloth** 2023-02-18 22:38 UTC
Labels: bug
