### ISSUE TITLE
Exception When Using Grenade Launcher

### ISSUE THREAD

**Issue by Unknown025** [Unknown025/Flans-Mod-Plus#29] opened 2021-04-01 21:40 UTC
Reported from CurseForge, adding here for consistency. Doesn't actually crash, causes a client/server disconnect.

[latest.log](https://pastebin.com/6XtW82vQ)
[Source](https://www.curseforge.com/minecraft/mc-mods/flans-mod-ultimate-stability-edition?comment=75)

**Comment by GoldSloth** [comment] 2021-04-01 22:45
I believe this is caused by #c3c65348ee304a6272a04f47966d0d0e9c298691. I will have a look at fixing it over the next few days, hopefully.
On a meta note, do you want to move bugs/crashes to the issue system in Github, and leave the trello board for features only?

**Comment by Unknown025** [comment] 2021-04-01 22:48
> I believe this is caused by #c3c65348ee304a6272a04f47966d0d0e9c298691. I will have a look at fixing it over the next few days, hopefully.
> On a meta note, do you want to move bugs/crashes to the issue system in Github, and leave the trello board for features only?

I personally prefer the GitHub system, it's easy to organize and specialized for this use case, but Trello's fine too. Whichever's easier for you.

**Comment by AHAPXNCT** [comment] 2021-04-27 08:08
Forge Exception When Using Grenade Launcher's from many pack's after updating version to 1.45 - client disconnect

**Comment by GoldSloth** [comment] 2021-04-28 21:51
Should be fixed in the next update.

**Closed as completed** 2021-05-05 03:22 UTC
Labels: bug
