### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#51] opened 2021-08-08 19:59 UTC
Tbh I don't know why this message appeared but I still wanted to send you the error since I thought you might be able to do something with it. It appeared a couple times btw.

>
[19:42:28 ERROR]: An Entity Bullet(com.flansmod.common.guns.EntityBullet) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1744) ~[sa.class:?]
	at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:172) [sg.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:487) [aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.7.0_221]
Caused by: java.lang.NullPointerException
	at com.flansmod.common.guns.BulletType.getBullet(BulletType.java:291) ~[BulletType.class:?]
	at com.flansmod.common.guns.EntityBullet.func_70037_a(EntityBullet.java:1217) ~[EntityBullet.class:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1662) ~[sa.class:?]
	... 12 more

**Comment by Unknown025** [comment] 2021-08-08 20:12
Interesting. Does this happen with a specific content pack, or to every single pack?

**Comment by pixelrider2000** [comment] 2021-08-09 11:59
Like I said, I really don't know why this message occured since I was just playing with the standard modern weapons content pack at the time. The error occured 5 times in total though it was the first and last time I ever saw it. 
I was just looking at the server log file again and I found out that before the error there were always these couple messages.

"
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : Flans-Simple-Parts-Pack-1.7.10.jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : MosPack
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : Flans-Zombie-Pack-1.7.10.jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : Flans-Modern-Weapons-Pack-1.7.10.jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : WW2-Content Pack-1.7.10-4.10.0.jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : Greylight_3.0.1-1.7.10.jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack : Machetemen-Arms-Pack-Mod-1.7.10 (1).jar
[19:38:31] [Server thread/INFO] [Flan's Mod Ultimate/]: Loaded content pack list server side.
[19:38:31] [Server thread/ERROR] [FML/]: An Entity Bullet(com.flansmod.common.guns.EntityBullet) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
net.minecraft.util.ReportedException: Loading entity NBT
"
I hope this helps but if there isn't a problem in the code I suppose I can't give you any more information on the issue.

**Comment by GoldSloth** [comment] 2021-08-09 12:21
These happen when a flying or dead bullet gets its data saved incorrectly - so when a chunk is being unloaded or the server is closing. The error happens when the server then tries to load these entities back in, and then ignores them because they're corrupt. The cause could be.. who knows. It's impossible to say effectively without getting a world save where it happens consistently, and the severity is extremely minor. I wouldn't worry about it unless you start seeing it very often. It would be nice to get it fixed tho e.e

It is more severe for EntityDriveable, Vehicle, Mecha, Plane because we don't want those randomly disappearing.

**Comment by pixelrider2000** [comment] 2021-08-09 12:35
Very interesting. Let me know if I can provide you with more helpful information. But I still agree that this problem is not very severe.

**Comment by GoldSloth** [comment] 2021-08-14 23:07
For now am not going to pursue it, so can this be closed now? Thanks ;)

**Closed as completed** 2021-08-15 00:21 UTC
Labels: bug
