### ISSUE TITLE
Config option for disabling tool tips / option to change the button 

### ISSUE THREAD

**Issue by pixelrider2000** [Unknown025/Flans-Mod-Plus#38] opened 2021-06-26 11:05 UTC
First of all I want to say that I really appreciate this version of Flans mod. It really bumps up the experience!
Anyways, the problem that I'm having has something to do with the tool tips that are being shown when pressing the "sneak-button" on an item. Often times when I am revealing these information by pressing shift, my game starts lagging/freezing for a couple of seconds. This makes it really hard to shift-drag items in and out of inventories. Although I don't know why that is, since my friend does not experience anything similar to that, **I would still love to see an option where I can disable and/or rebind this feature.**

If it can already be disabled/rebound or you have an idea why it's lagging, please let me know.

Appreciate your work and efforts!

**EDIT:** I just found out that if I hold down the "tool tip-Key/shift" and then search something in the minecraft search bar, my game crashes.

**Comment by GoldSloth** [comment] 2021-06-26 11:31
Currently I don't think there is an option for that, apart from mags/bullets where you can set `FancyDescription false` in their config. Otherwise, I think a global option would be a good idea, but I'm interested to know about the lag you get from pressing shift on these items. Does it happen every time, or just the first time?
If you'd be able to provide some information about system specs, how much ram is assigned to minecraft, what other mods you're using and whether it happens for some or all guns - and from what pack, that'd be really helpful.

**Comment by pixelrider2000** [comment] 2021-06-26 11:41
Lag only occures the first time I reveal the tool tips on an item. After that there are no problems with that specific gun/ammo. Furthermore I've allocated 4 GB of RAM and apart from that, my game and system is running smoothly. Apart from your Flans Mod version (1.45) and Custom NPC, I only have content packs installed. The lag also happens to occur on all guns.

I also want to mention the edit on my first post if you havn't seen it already.

**Comment by GoldSloth** [comment] 2021-06-26 12:20
Okay, thank you, I'll look into it. And just a last few details, are you using a resource pack, optifine and what content packs are you using?

**Comment by pixelrider2000** [comment] 2021-06-26 12:37
I am using both a resource pack and optifine (When I remove optifine, the lag still persists). 

These are my content packs:
- MosPack
- Flans-Modern-Weapons-Pack-1.7.10
- Flans-Simple-Parts-Pack-1.7.10
- Flans-Zombie-Pack-1.7.10
- Greylight_3.0.1-1.7.10
- Machetemen-Arms-Pack-Mod-1.7.10
- WW2-Content Pack-1.7.10-4.10.0

EDIT: I will now do some testing to see if removing some content packs helps (I'll update you if I make a discovery)

**Comment by pixelrider2000** [comment] 2021-06-26 12:58
UPDATE: I pinpointed the issue down to the Machetemen-Arms content pack. Apparently does adding this pack cause this weird lag. Still, since I rather not want to remove this pack from my server, I'd like to see a feature that allows me to remove or rebind this feature.

Though, I would really appreciate you taking a look at this content pack. I have this notion that it might have something to do with the gun configs in this pack (maybe something is missing or else).
Here is the pack: https://www.mediafire.com/file/l8yjckltz9j3ypx/Machetemen-Arms-Pack-Mod-1.7.10.jar/file

Maybe you can tell me what's wrong with this pack. Thanks a lot!

**Comment by pixelrider2000** [comment] 2021-06-26 13:45
FIXED IT! I think I have it. The problem was that I removed some ammo from the pack (that I thought was useless). Anyways, my "tool tip remove idea" is still there and I hope you take it into consideration ;) Plus, maybe you could look into this issue and make it so that if ammo is missing, this lag doesn't occur. Please let me know if that was indeed the problem, since I'm really interested in that! Thanks for helping me anyways, your work's amazing!

**Comment by GoldSloth** [comment] 2021-06-26 14:36
Ah! Thank you for your troubleshooting. The cause is probably the algorithm used to match up the compatible ammo to the gun, and since mpack introduces a lot of both, it's pretty laggy. I'll look into improving that, but also disabling that feature either partly or as a whole. Many thanks :)

**Comment by GoldSloth** [comment] 2021-06-27 11:35
Correction to my previous message, it's actually the code trying to find which gunbox the item's in. It searches every single gunbox entry in the game, which can be pretty slow.

**Comment by GoldSloth** [comment] 2021-06-27 13:13
[1.47-test.zip](https://github.com/Unknown025/Flans-Mod-Plus/files/6721626/1.47-test.zip)
Would you mind testing this build? I'm hoping it'll fix the lag to some degree.

**Comment by pixelrider2000** [comment] 2021-07-01 14:02
Sorry I'm answering this late! I'm just not this active on github (yet :) ). Anyways, it seems to be fixed though 👍 
EDIT: Just wanted to mention that there appears to be no lag, like at all!

**Comment by GoldSloth** [comment] 2021-07-01 16:27
No problem, thanks for testing it! The full fix will be in the next update, until then you can use the build I provided.  Just be aware it could have strange things that I forgot to take out of it for debugging e.e

**Comment by GoldSloth** [comment] 2021-07-05 19:47
Okay, this config has been added to flansmod.cfg

```
    # Whether to show fancy item descriptions. These can be shown by pressing shift on an item ingame. [default: true]
    B:"Enable fancy descriptions"=false
```

**Comment by GoldSloth** [comment] 2021-07-05 19:48
Should be out in the next release, let me know if you've got any more questions, bug reports or feature requests ;)

**Closed as completed by GoldSloth** 2021-07-05 19:48 UTC
Labels: enhancement
